
pipeline {

agent any

environment {

DOCKER_IMAGE = "yourdockerhub/tetris"
DOCKER_TAG = "latest"

}

tools {
nodejs 'node24'
}

stages {

stage('Checkout Code') {
steps {
git 'https://github.com/yourusername/devsecops-tetris-eks.git'
}
}

stage('Install Dependencies') {
steps {
sh 'npm install'
}
}

stage('SonarQube Analysis') {
steps {
withSonarQubeEnv('sonar-server') {
sh 'sonar-scanner'
}
}
}

stage('OWASP Dependency Check') {
steps {
dependencyCheck additionalArguments: '--scan ./'
}
}

stage('Trivy File Scan') {
steps {
sh 'trivy fs .'
}
}

stage('Build Docker Image') {
steps {
sh 'docker build -t $DOCKER_IMAGE:$DOCKER_TAG .'
}
}

stage('Push Docker Image') {
steps {
withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'PASS', usernameVariable: 'USER')]) {

sh '''
docker login -u $USER -p $PASS
docker push $DOCKER_IMAGE:$DOCKER_TAG
'''
}
}
}

stage('Trivy Image Scan') {
steps {
sh 'trivy image $DOCKER_IMAGE:$DOCKER_TAG'
}
}

stage('Update Kubernetes Manifest') {
steps {
sh '''
sed -i "s|image:.*|image: $DOCKER_IMAGE:$DOCKER_TAG|" kubernetes/deployment.yml
'''
}
}

}

}
